/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VideosVideoIdImport } from './routes/videos/$videoId'
import { Route as ProgramsProgramIdImport } from './routes/programs/$programId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const WorkoutIndexLazyImport = createFileRoute('/workout/')()
const VideoDetailIndexLazyImport = createFileRoute('/video-detail/')()
const SignUpIndexLazyImport = createFileRoute('/sign-up/')()
const SignInIndexLazyImport = createFileRoute('/sign-in/')()
const ProgressIndexLazyImport = createFileRoute('/progress/')()
const ProgramsIndexLazyImport = createFileRoute('/programs/')()
const ProfileIndexLazyImport = createFileRoute('/profile/')()
const PersonalDataIndexLazyImport = createFileRoute('/personal-data/')()
const HelpCenterIndexLazyImport = createFileRoute('/help-center/')()
const DashboardIndexLazyImport = createFileRoute('/dashboard/')()
const CollectionsIndexLazyImport = createFileRoute('/collections/')()
const BookingSuccessfulIndexLazyImport = createFileRoute(
  '/booking-successful/',
)()
const AccountIndexLazyImport = createFileRoute('/account/')()
const AboutIndexLazyImport = createFileRoute('/about/')()
const VideoDetailVideoFeedbackIndexLazyImport = createFileRoute(
  '/video-detail/video-feedback/',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const WorkoutIndexLazyRoute = WorkoutIndexLazyImport.update({
  path: '/workout/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/workout/index.lazy').then((d) => d.Route))

const VideoDetailIndexLazyRoute = VideoDetailIndexLazyImport.update({
  path: '/video-detail/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/video-detail/index.lazy').then((d) => d.Route),
)

const SignUpIndexLazyRoute = SignUpIndexLazyImport.update({
  path: '/sign-up/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sign-up/index.lazy').then((d) => d.Route))

const SignInIndexLazyRoute = SignInIndexLazyImport.update({
  path: '/sign-in/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sign-in/index.lazy').then((d) => d.Route))

const ProgressIndexLazyRoute = ProgressIndexLazyImport.update({
  path: '/progress/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/progress/index.lazy').then((d) => d.Route),
)

const ProgramsIndexLazyRoute = ProgramsIndexLazyImport.update({
  path: '/programs/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/programs/index.lazy').then((d) => d.Route),
)

const ProfileIndexLazyRoute = ProfileIndexLazyImport.update({
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile/index.lazy').then((d) => d.Route))

const PersonalDataIndexLazyRoute = PersonalDataIndexLazyImport.update({
  path: '/personal-data/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/personal-data/index.lazy').then((d) => d.Route),
)

const HelpCenterIndexLazyRoute = HelpCenterIndexLazyImport.update({
  path: '/help-center/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/help-center/index.lazy').then((d) => d.Route),
)

const DashboardIndexLazyRoute = DashboardIndexLazyImport.update({
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)

const CollectionsIndexLazyRoute = CollectionsIndexLazyImport.update({
  path: '/collections/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/collections/index.lazy').then((d) => d.Route),
)

const BookingSuccessfulIndexLazyRoute = BookingSuccessfulIndexLazyImport.update(
  {
    path: '/booking-successful/',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/booking-successful/index.lazy').then((d) => d.Route),
)

const AccountIndexLazyRoute = AccountIndexLazyImport.update({
  path: '/account/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/account/index.lazy').then((d) => d.Route))

const AboutIndexLazyRoute = AboutIndexLazyImport.update({
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about/index.lazy').then((d) => d.Route))

const VideosVideoIdRoute = VideosVideoIdImport.update({
  path: '/videos/$videoId',
  getParentRoute: () => rootRoute,
} as any)

const ProgramsProgramIdRoute = ProgramsProgramIdImport.update({
  path: '/programs/$programId',
  getParentRoute: () => rootRoute,
} as any)

const VideoDetailVideoFeedbackIndexLazyRoute =
  VideoDetailVideoFeedbackIndexLazyImport.update({
    path: '/video-detail/video-feedback/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/video-detail/video-feedback/index.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/programs/$programId': {
      id: '/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdImport
      parentRoute: typeof rootRoute
    }
    '/videos/$videoId': {
      id: '/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/videos/$videoId'
      preLoaderRoute: typeof VideosVideoIdImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/booking-successful/': {
      id: '/booking-successful/'
      path: '/booking-successful'
      fullPath: '/booking-successful'
      preLoaderRoute: typeof BookingSuccessfulIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/help-center/': {
      id: '/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/personal-data/': {
      id: '/personal-data/'
      path: '/personal-data'
      fullPath: '/personal-data'
      preLoaderRoute: typeof PersonalDataIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/progress/': {
      id: '/progress/'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/video-detail/': {
      id: '/video-detail/'
      path: '/video-detail'
      fullPath: '/video-detail'
      preLoaderRoute: typeof VideoDetailIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/workout/': {
      id: '/workout/'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/video-detail/video-feedback/': {
      id: '/video-detail/video-feedback/'
      path: '/video-detail/video-feedback'
      fullPath: '/video-detail/video-feedback'
      preLoaderRoute: typeof VideoDetailVideoFeedbackIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ProgramsProgramIdRoute,
  VideosVideoIdRoute,
  AboutIndexLazyRoute,
  AccountIndexLazyRoute,
  BookingSuccessfulIndexLazyRoute,
  CollectionsIndexLazyRoute,
  DashboardIndexLazyRoute,
  HelpCenterIndexLazyRoute,
  PersonalDataIndexLazyRoute,
  ProfileIndexLazyRoute,
  ProgramsIndexLazyRoute,
  ProgressIndexLazyRoute,
  SignInIndexLazyRoute,
  SignUpIndexLazyRoute,
  VideoDetailIndexLazyRoute,
  WorkoutIndexLazyRoute,
  VideoDetailVideoFeedbackIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/programs/$programId",
        "/videos/$videoId",
        "/about/",
        "/account/",
        "/booking-successful/",
        "/collections/",
        "/dashboard/",
        "/help-center/",
        "/personal-data/",
        "/profile/",
        "/programs/",
        "/progress/",
        "/sign-in/",
        "/sign-up/",
        "/video-detail/",
        "/workout/",
        "/video-detail/video-feedback/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/programs/$programId": {
      "filePath": "programs/$programId.tsx"
    },
    "/videos/$videoId": {
      "filePath": "videos/$videoId.tsx"
    },
    "/about/": {
      "filePath": "about/index.lazy.tsx"
    },
    "/account/": {
      "filePath": "account/index.lazy.tsx"
    },
    "/booking-successful/": {
      "filePath": "booking-successful/index.lazy.tsx"
    },
    "/collections/": {
      "filePath": "collections/index.lazy.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.lazy.tsx"
    },
    "/help-center/": {
      "filePath": "help-center/index.lazy.tsx"
    },
    "/personal-data/": {
      "filePath": "personal-data/index.lazy.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.lazy.tsx"
    },
    "/programs/": {
      "filePath": "programs/index.lazy.tsx"
    },
    "/progress/": {
      "filePath": "progress/index.lazy.tsx"
    },
    "/sign-in/": {
      "filePath": "sign-in/index.lazy.tsx"
    },
    "/sign-up/": {
      "filePath": "sign-up/index.lazy.tsx"
    },
    "/video-detail/": {
      "filePath": "video-detail/index.lazy.tsx"
    },
    "/workout/": {
      "filePath": "workout/index.lazy.tsx"
    },
    "/video-detail/video-feedback/": {
      "filePath": "video-detail/video-feedback/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
